name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Se activa cuando subes cambios a la rama main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: . # Ubicación de tu proyecto Astro
          node-version: 20 # Versión recomendada para Astro 5