name: Deploy to GitHub Pages
on:
  push:
    branches: [main] # Asegúrate de que tu rama se llame main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: .
          node-version: 20